language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging

# Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy


# Tagging
  - docker tag udagram-api-feed  oreaba/udagram-api-feed:v1
  - docker tag udagram-api-user  oreaba/udagram-api-user:v1
  - docker tag udagram-frontend  oreaba/udagram-frontend:v1
  - docker tag udagram-reverseproxy oreaba/udagram-reverseproxy:v1


# Push
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push oreaba/udagram-api-feed:v1 
  - docker push oreaba/udagram-api-user:v1
  - docker push oreaba/udagram-frontend:v1 
  - docker push oreaba/udagram-reverseproxy:v1

after_success:
  - echo "no tests"
