apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      service: reverseproxy
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
      - image: docker.io/oreaba/udagram-reverseproxy:v3
        name: reverseproxy
        imagePullPolicy: Always          
        resources:
          limits:
            cpu: "500m"                  
          requests:
            cpu: "250m"     
        ports:
        - containerPort: 8080
      restartPolicy: Always

